
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package smpl.lang;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int MOD = 11;
  public static final int AND = 21;
  public static final int LT = 17;
  public static final int NOTEQ = 20;
  public static final int PLUS = 7;
  public static final int OR = 22;
  public static final int RPAREN = 4;
  public static final int SEMI = 2;
  public static final int NOT = 23;
  public static final int IDENTIFIER = 5;
  public static final int LPAREN = 3;
  public static final int GT = 16;
  public static final int TILDE = 14;
  public static final int AMP = 12;
  public static final int LTEQ = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 10;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int ASSIGN = 24;
  public static final int EQ = 15;
  public static final int INTEGER_LITERAL = 6;
  public static final int GTEQ = 19;
  public static final int BAR = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "AMP",
  "BAR",
  "TILDE",
  "EQ",
  "GT",
  "LT",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "AND",
  "OR",
  "NOT",
  "ASSIGN"
  };
}

